#!/usr/bin/env bash
# Build (and, when the ceremony cert exists, sign) the things-deputy broker.
#
# Output: deputy/build/things-deputy
#
# Signing: TCC grants attach to the responsible process's code signature, so
# the deputy MUST be signed with the persistent self-signed certificate minted
# by scripts/deputy-cert-setup.sh ("things-deputy-signing") for grants to
# survive rebuilds. Ad-hoc signing is deliberately NOT used — an ad-hoc
# identity changes on every build, which silently re-introduces the TCC churn
# the deputy exists to end. An unsigned build still runs (useful for tests),
# but macOS treats each new binary hash as a new grantee.
set -euo pipefail

cd "$(dirname "$0")/.."

VERSION=$(node -p "require('./package.json').version")
BUILD_DIR=deputy/build
mkdir -p "$BUILD_DIR"

cat >"$BUILD_DIR/Version.swift" <<EOF
// Generated by scripts/build-deputy.sh — do not edit, not committed.
let DEPUTY_VERSION = "$VERSION"
EOF

echo "building things-deputy $VERSION..."
swiftc -O deputy/src/*.swift "$BUILD_DIR/Version.swift" -o "$BUILD_DIR/things-deputy"

IDENTITY="things-deputy-signing"
if security find-identity -v -p codesigning 2>/dev/null | grep -q "$IDENTITY"; then
  echo "signing with $IDENTITY..."
  codesign --force --sign "$IDENTITY" \
    --identifier com.pixelcog.things-deputy \
    "$BUILD_DIR/things-deputy"
  codesign --verify --verbose=1 "$BUILD_DIR/things-deputy"
else
  echo "WARNING: signing identity '$IDENTITY' not found — binary is UNSIGNED." >&2
  echo "TCC grants will not survive rebuilds. Run scripts/deputy-cert-setup.sh once, then rebuild." >&2
fi

echo "built $BUILD_DIR/things-deputy"
