#!/usr/bin/env bash
# Build (and, when the ceremony cert exists, sign) the things-deputy broker.
#
# Output: deputy/build/things-deputy
#
# Signing: TCC grants attach to the responsible process's code signature, so
# the deputy MUST be signed with the persistent self-signed certificate minted
# by scripts/deputy-cert-setup.sh ("things-deputy-signing") for grants to
# survive rebuilds. Ad-hoc signing is deliberately NOT used — an ad-hoc
# identity changes on every build, which silently re-introduces the TCC churn
# the deputy exists to end. An unsigned build still runs (useful for tests),
# but macOS treats each new binary hash as a new grantee.
set -euo pipefail

cd "$(dirname "$0")/.."

VERSION=$(node -p "require('./package.json').version")
BUILD_DIR=deputy/build
mkdir -p "$BUILD_DIR"

cat >"$BUILD_DIR/Version.swift" <<EOF
// Generated by scripts/build-deputy.sh — do not edit, not committed.
let DEPUTY_VERSION = "$VERSION"
EOF

echo "building things-deputy $VERSION..."
# Compile to a temp name and only move the SIGNED result into place: swiftc
# output is deterministic, so the unsigned intermediate reproduces a hash an
# EDR may already have convicted — signing before the final path exists keeps
# the deliverable path clean and shrinks the unsigned-on-disk window.
UNSIGNED="$BUILD_DIR/.things-deputy.build.$$"
trap 'rm -f "$UNSIGNED"' EXIT
swiftc -O deputy/src/*.swift "$BUILD_DIR/Version.swift" -o "$UNSIGNED"

# Identity preference: Developer ID Application (distribution-grade, 5-year,
# notarizable) > Apple Development (Apple-issued dev cert) > the self-signed
# ceremony cert. All three are STABLE identities so TCC grants survive
# rebuilds; ad-hoc signing is never used (identity would churn per build).
IDENTITY=""
for candidate in "Developer ID Application" "Apple Development" "things-deputy-signing"; do
  if security find-identity -v -p codesigning 2>/dev/null | grep -q "$candidate"; then
    IDENTITY="$candidate"
    break
  fi
done

if [ -n "$IDENTITY" ]; then
  echo "signing with '$IDENTITY' (hardened runtime + timestamp)..."
  codesign --force --sign "$IDENTITY" \
    --identifier com.pixelcog.things-deputy \
    --options runtime --timestamp \
    "$UNSIGNED"
  codesign --verify --verbose=1 "$UNSIGNED"
else
  echo "WARNING: no signing identity found — binary is UNSIGNED." >&2
  echo "TCC grants will not survive rebuilds. Create a Developer ID Application cert in Xcode," >&2
  echo "or run scripts/deputy-cert-setup.sh for a local self-signed one, then rebuild." >&2
fi

rm -f "$BUILD_DIR/things-deputy"
mv "$UNSIGNED" "$BUILD_DIR/things-deputy"
trap - EXIT
echo "built $BUILD_DIR/things-deputy"

# --- things-reader: the sandboxed file half (deputy/reader/) -----------------
# Ships as a minimal .app bundle (secinit refuses bare executables) and MUST
# carry a real certificate chain (amfid refuses ad-hoc on sandboxed code) —
# SANDBOX1, docs/lab/sandbox1-scoped-reader.md. Unsigned hosts skip the reader
# rather than produce a bundle macOS would kill at exec.
if [ -n "$IDENTITY" ]; then
  echo "building things-reader $VERSION..."
  APP="$BUILD_DIR/things-reader.app"
  rm -rf "$APP"
  mkdir -p "$APP/Contents/MacOS"
  sed "s/<string>0\.0\.0<\/string>/<string>$VERSION<\/string>/" \
    deputy/reader/Info.plist > "$APP/Contents/Info.plist"
  swiftc -O deputy/reader/main.swift deputy/src/sqlite.swift "$BUILD_DIR/Version.swift" \
    -o "$APP/Contents/MacOS/things-reader"
  codesign --force --sign "$IDENTITY" \
    --options runtime --timestamp \
    --entitlements deputy/reader/entitlements.plist \
    "$APP"
  codesign --verify --verbose=1 "$APP"
  echo "built $APP"
else
  echo "WARNING: skipping things-reader — sandboxed code cannot run without a real signing chain." >&2
fi
