#!/usr/bin/env bash
# Build (and sign) the things-helpers bundle — ONE .app housing both helpers:
# the unsandboxed things-deputy (automation verbs) as the bundle's main
# executable, and the sandboxed things-reader.app (file verbs) nested under
# Contents/Helpers with its own bundle identity + entitlements.
#
# Output: deputy/build/Things API Helper.app
#
# Signing: TCC grants attach to the responsible code identity, so the bundle
# MUST carry a stable identity for grants to survive rebuilds — ad-hoc is
# deliberately never used (its identity churns per build). The nested reader
# additionally REQUIRES an Apple-issued chain: amfid refuses ad-hoc AND
# self-signed roots on sandboxed code (SANDBOX1, docs/lab/
# sandbox1-scoped-reader.md), so a host with only the self-signed ceremony
# cert gets a deputy-only bundle. The reader's bundle identifier
# (com.pixelcog.things-reader) must never change — the user's security-scoped
# bookmark grant is keyed to it.
set -euo pipefail

cd "$(dirname "$0")/.."

# The helpers' OWN version line (deputy/VERSION) — deliberately decoupled from
# package.json so a package release with unchanged helper sources produces an
# equivalently versioned bundle and never nags for a reinstall.
VERSION=$(tr -d '[:space:]' < deputy/VERSION)
BUILD_DIR=deputy/build
mkdir -p "$BUILD_DIR"

cat >"$BUILD_DIR/Version.swift" <<EOF
// Generated by scripts/build-helpers.sh — do not edit, not committed.
let DEPUTY_VERSION = "$VERSION"
EOF

# Identity preference: Developer ID Application (distribution-grade, 5-year,
# notarizable) > Apple Development (Apple-issued dev cert) > the self-signed
# ceremony cert (scripts/deputy-cert-setup.sh; deputy-only — see above).
IDENTITY=""
APPLE_CHAIN=0
for candidate in "Developer ID Application" "Apple Development"; do
  if security find-identity -v -p codesigning 2>/dev/null | grep -q "$candidate"; then
    IDENTITY="$candidate"
    APPLE_CHAIN=1
    break
  fi
done
if [ -z "$IDENTITY" ] &&
  security find-identity -v -p codesigning 2>/dev/null | grep -q "things-deputy-signing"; then
  IDENTITY="things-deputy-signing"
fi

# Assemble under a temp name and only move the SIGNED bundle into place:
# swiftc output is deterministic, so an unsigned intermediate at the final
# path reproduces a hash an EDR may already have convicted — signing before
# the deliverable path exists keeps that path clean.
STAGE="$BUILD_DIR/.things-helpers.build.$$"
trap 'rm -rf "$STAGE"' EXIT
rm -rf "$STAGE"
APP="$STAGE/Things API Helper.app"
mkdir -p "$APP/Contents/MacOS"

echo "building things-deputy $VERSION..."
sed "s/<string>0\.0\.0<\/string>/<string>$VERSION<\/string>/" \
  deputy/helpers-Info.plist > "$APP/Contents/Info.plist"
swiftc -O deputy/src/*.swift "$BUILD_DIR/Version.swift" -o "$APP/Contents/MacOS/things-deputy"
# Icon must land before signing — the outer signature seals bundle resources.
mkdir -p "$APP/Contents/Resources"
cp deputy/AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"

if [ "$APPLE_CHAIN" = "1" ]; then
  echo "building things-reader $VERSION..."
  READER="$APP/Contents/Helpers/things-reader.app"
  mkdir -p "$READER/Contents/MacOS"
  sed "s/<string>0\.0\.0<\/string>/<string>$VERSION<\/string>/" \
    deputy/reader/Info.plist > "$READER/Contents/Info.plist"
  swiftc -O deputy/reader/main.swift deputy/src/sqlite.swift "$BUILD_DIR/Version.swift" \
    -o "$READER/Contents/MacOS/things-reader"
  mkdir -p "$READER/Contents/Resources"
  cp deputy/AppIcon.icns "$READER/Contents/Resources/AppIcon.icns"
  # Nested-first signing order (never --deep): the reader carries its own
  # sandbox entitlements; the outer signature then seals the whole bundle.
  codesign --force --sign "$IDENTITY" \
    --options runtime --timestamp \
    --entitlements deputy/reader/entitlements.plist \
    "$READER"
else
  echo "WARNING: skipping things-reader — sandboxed code cannot run without an Apple-issued certificate chain." >&2
  echo "File reads will run direct. Add an Apple Development cert (free Apple ID via Xcode) and rebuild." >&2
fi

if [ -n "$IDENTITY" ]; then
  echo "signing Things API Helper.app with '$IDENTITY' (hardened runtime + timestamp)..."
  codesign --force --sign "$IDENTITY" \
    --identifier com.pixelcog.things-api-helper \
    --options runtime --timestamp \
    "$APP"
  codesign --verify --verbose=1 "$APP"
else
  echo "WARNING: no signing identity found — bundle is UNSIGNED." >&2
  echo "TCC grants will not survive rebuilds. Create a Developer ID Application cert in Xcode," >&2
  echo "or run scripts/deputy-cert-setup.sh for a local self-signed one, then rebuild." >&2
fi

# Fresh inode for the deliverable (the kernel caches signature state per
# vnode), and clear any pre-bundle build outputs so nothing stale lingers.
rm -rf "$BUILD_DIR/Things API Helper.app" "$BUILD_DIR/things-helpers.app" "$BUILD_DIR/things-deputy" "$BUILD_DIR/things-reader.app"
mv "$APP" "$BUILD_DIR/Things API Helper.app"
rm -rf "$STAGE"
trap - EXIT
echo "built $BUILD_DIR/Things API Helper.app"
