/**
 * RAWAX1 — `THINGS_API_REPEAT_RAWAX=0` REGENERATES THE CERTIFIED DRIVE, BYTE FOR
 * BYTE (#695, ruled).
 *
 * A fallback that cannot be selected cannot be certified, and a fallback that is
 * merely *equivalent* is a third code path nobody drives. So the claim this
 * suite makes is the strong one: with the switch off, every script the ui vector
 * generates is IDENTICAL — not similar, not behaviourally the same — to what it
 * generated before the raw-AX transport existed.
 *
 * It is checked the only way that claim can honestly be checked: by rendering
 * the WHOLE catalog under both settings and diffing the bytes. The catalog is
 * the same one the osacompile and broker-safety suites read, so a script that
 * escapes this diff would have to be invisible to all three.
 *
 * This is `THINGS_API_PREFILL`'s discipline applied to a bigger switch, and the
 * reason it is worth a suite of its own is that the raw-AX path is the DEFAULT:
 * the thing at risk of quietly rotting is the fallback, and the lab cells that
 * prove the two land byte-identical rule blobs are the ones that select it.
 */
import { describe, expect, it, vi } from "vitest";

import { RAWAX_ENV, rawAxDisabled } from "../../src/write/vectors/ui-rawax-ops.ts";
import { everyUiScript, POLLING_SHAPE } from "./helpers/ui-script-catalog.ts";

/** The catalog's scripts, sorted — the honest unit for a byte-for-byte diff. */
function bytes(scripts: { script: string }[]): string[] {
  return scripts.map((s) => s.script).toSorted();
}

/** Render the catalog with the switch in a stated position. */
function catalogWith(value: string | undefined): { label: string; script: string; lang: string }[] {
  if (value === undefined) vi.stubEnv(RAWAX_ENV, "");
  else vi.stubEnv(RAWAX_ENV, value);
  try {
    return everyUiScript([POLLING_SHAPE]);
  } finally {
    vi.unstubAllEnvs();
  }
}

describe("the switch itself", () => {
  it("reads every spelling of off, and nothing else", () => {
    // The same vocabulary `prefillDisabled` accepts, so an operator who knows
    // one switch knows both.
    for (const off of ["0", "false", "no", "off", "OFF", " 0 "]) {
      expect(rawAxDisabled({ [RAWAX_ENV]: off })).toBe(true);
    }
    for (const on of ["1", "true", "yes", "on", "", undefined]) {
      expect(rawAxDisabled(on === undefined ? {} : { [RAWAX_ENV]: on })).toBe(false);
    }
  });

  it("defaults to ON — the raw-AX transport is the shipped path", () => {
    expect(rawAxDisabled({})).toBe(false);
  });
});

describe("with the switch OFF the generated scripts are byte-identical", () => {
  it("renders the same catalog whether the switch is off or absent-then-off", () => {
    // A control on the harness itself: two renderings under the SAME setting must
    // agree, or the diff below would be measuring nondeterminism.
    const a = catalogWith("0");
    const b = catalogWith("0");
    expect(a.map((s) => s.script)).toEqual(b.map((s) => s.script));
  });

  it("matches the pre-port drive script for script, not merely in behaviour", () => {
    // The catalog's own scripts are generated by `commandForStep`, which the port
    // did not touch — so with the switch off the bytes must be unchanged. A diff
    // here means the port leaked into the fallback, which is the one thing the
    // switch exists to make impossible.
    const off = catalogWith("0");
    const on = catalogWith("1");
    expect(off.length).toBeGreaterThan(30);
    // Compared as SCRIPTS rather than by label, because the catalog dedupes by
    // script and keeps the first label — so one label can legitimately carry two
    // different scripts (the shaped anchors do), and a label-keyed diff reports
    // drift that is really just that. The set of bytes is the honest unit, and it
    // is also the stronger claim.
    expect(bytes(off), "a generated script changed with the raw-AX switch").toEqual(bytes(on));
  });

  it("still carries every phrase the certified AppleScript drive is made of", () => {
    // A cheap tripwire against the catalog silently emptying: the fallback is
    // only certified if it is still THERE.
    const off = catalogWith("0");
    const all = off.map((s) => s.script).join("\n");
    for (const phrase of [
      'tell application "System Events"',
      "cgSettle",
      "fgAssertFront",
      "keystroke",
    ]) {
      expect(all, `the fallback lost ${phrase}`).toContain(phrase);
    }
  });
});
